<a href="https://colab.research.google.com/github/juansevargasc/IntroduccionSI/blob/main/%5BJuanse%5DTaller_4_clustering_Juan_Sebastian_Vargas_Casta%C3%B1eda.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Taller 4: Clustering
## [Introducción a los Sistemas Inteligentes 2021-1](https://fagonzalezo.github.io/iis-2021-1/)


In [ ]:
import pandas as pd
import numpy as np


In [ ]:
#TEST CELL
try:
  import google.colab
  IN_COLAB = True
except:
  IN_COLAB = False

if IN_COLAB:
    !wget https://sites.google.com/a/unal.edu.co/mineria-de-datos-2012-2/credit-german.csv

--2021-06-21 16:54:40--  https://sites.google.com/a/unal.edu.co/mineria-de-datos-2012-2/credit-german.csv
Resolving sites.google.com (sites.google.com)... 172.217.218.113, 172.217.218.138, 172.217.218.100, ...
Connecting to sites.google.com (sites.google.com)|172.217.218.113|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://sites.google.com/a/unal.edu.co/mineria-de-datos-2012-2/credit-german.csv?attredirects=0 [following]
--2021-06-21 16:54:40--  https://sites.google.com/a/unal.edu.co/mineria-de-datos-2012-2/credit-german.csv?attredirects=0
Reusing existing connection to sites.google.com:443.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://e6c3d1db-a-f56cbe42-s-sites.googlegroups.com/a/unal.edu.co/mineria-de-datos-2012-2/credit-german.csv?attachauth=ANoY7cr0DyCO-KvjTm5EmKuBPpAJXM9-oQLk2UoDTpnbzbMrvZdoEJVjKAdHlXKcMnRj3UfpaOl05pqaJTwYXLWYTepqn9vv2ryAY4Pe_H2bFutr0k1aQMYrk0BBQxEpGG4Q95EPvyeRW1yYI9uQ2VK-_TEvzty

Primero vamos a leer un conjunto de datos para scoring de crédito:

In [ ]:
df = pd.read_csv("credit-german.csv", sep=";")
df

checking_status  disc_duration  ... foreign_worker class
0                <0              6  ...            yes  good
1          0<=X<200             48  ...            yes   bad
2       no checking             12  ...            yes  good
3                <0             42  ...            yes  good
4                <0             24  ...            yes   bad
..              ...            ...  ...            ...   ...
995     no checking             12  ...            yes  good
996              <0             30  ...            yes  good
997     no checking             12  ...            yes  good
998              <0             45  ...            yes   bad
999        0<=X<200             45  ...            yes  good

[1000 rows x 19 columns]

Procesamos el dataframe para convertir las variables categóricas en númericas usando one-hot-encoding (variables binarias representando cada valor de una variable categórica):

In [ ]:
df = pd.get_dummies(df)
df

disc_duration  credit_amount  ...  class_bad  class_good
0                6           1169  ...          0           1
1               48           5951  ...          1           0
2               12           2096  ...          0           1
3               42           7882  ...          0           1
4               24           4870  ...          1           0
..             ...            ...  ...        ...         ...
995             12           1736  ...          0           1
996             30           3857  ...          0           1
997             12            804  ...          0           1
998             45           1845  ...          1           0
999             45           4576  ...          0           1

[1000 rows x 65 columns]

## 1. Escale los datos
Cree una función que reciba el dataframe con los datos y retorne un arreglo de numpy con los datos. Los datos deben estar escalados de manera que para cada columna el menor valor es 0 y el mayor 1.


In [ ]:
from sklearn.preprocessing import MinMaxScaler

def escalar(df):
    '''
    df: dataframe con los datos
    Returns:
    X: arreglo de numpy con los datos escalados
    '''

    ## Your code here
    scaler = MinMaxScaler()
    X = np.array(scaler.fit_transform(df))
    return X



## 2. Entrene un modelo de agrupamiento

Escriba una función que reciba la matriz de datos y entrene un modelo de clustering. La función debe retornar el modelo entrenado.

In [ ]:
from sklearn.cluster import KMeans

def clustering(X, k):
    '''
    X: arreglo de numpy con los datos 
    k: número de clusters
    Returns:
    km: instancia de KMeans entrenada con X
    '''
    ## Your code here
    km = KMeans(n_clusters=k)
    km.fit(X)
    
    return km


## 3. Calcule el número de elementos en cada cluster

Escriba una función de que reciba un modelo entrenado de clustering y un conjunto de datos. Aplique el modelo de clustering a los datos (no debe reentrenar solo predecir) y calcule cuantos datos quedaron en cada cluster.

In [ ]:
def num_elems(km, X):
    '''
    km: modelo KMeans preentrenado
    X: arreglo de numpy con los datos 

    Returns:
    num: arreglo de numpy con el número de datos por cluster
    '''
    ## Your code here
    y = km.predict(X)
    num = np.bincount(y)
    return num



# 4. Calcule los centroides

Escriba una función que reciba un modelo de KMeans entrenado y retorne un centroide de un cluster particular.

In [ ]:
def centroid(km, n):
    '''
    km: modelo KMeans preentrenado
    n: índice del cluster

    Returns:
    centroid: arreglo de numpy con el centroide del cluster
    '''
    ## Your code here
    centroid = np.array(km.cluster_centers_)[n]
    return centroid



# 5. Calcule las edades promedio de cada cluster
Escriba una función que calcule la edad promedio de las muestras en cada cluster. Estas edades deben ser reportadas en la escala original. La función debe recibir un modelo entrenado (usando los datos escalados) y los datos escalados usados para entrenar el modelo y debe retornar un vector con las edades promedio de cada cluster. Las edades deben estar en las escala original (no escaladas entre 0 y 1).

In [ ]:
def age(km, X):
    '''
    km: modelo KMeans preentrenado
    X: arreglo de numpy con los datos escalados

    Returns:
    ages: arreglo de numpy con el valor de las edades promedio
    '''
    

    ## Your code here
    y = km.predict(X)
    Xun = escaler.inverse_transform(X) # desnormaliza los datos
    ages = []
    for i in (np.unique(y)): # Recorre cada cluster
      cluage = Xun[np.argwhere(y == i), 2] #np.arg where obtiene los indices donde está cada dato del cluster y Xun[npw, 2] guarda las edades que pertenecen al cluster
      ages.append(np.mean(cluage))
    ages = np.array(ages)
    return ages



## 6. Calcule el porcentaje de malos deudores en cada cluster

Escriba una función que calcule el porcentaje de malos deudores en cada uno de los clusters. La función recibe un modelo preentrenado y los datos usados para entrenar el modelo y debe retornar un vector con los porcentajes.

In [ ]:
def classes(km, X):
    '''
    km: modelo KMeans preentrenado
    X: arreglo de numpy con los datos 

    Returns:
    percentages: arreglo de numpy con el valor de los porcentajes
    '''
    ## Your code here
    y = km.predict(X)
    percentages=[]
    for i in (np.unique(y)): #Recorre cada cluster
      badclass = X[np.argwhere(y == i), -2] #np.arg where obtiene los indices donde está cada dato del cluster y Xun[npw, 2] guarda los malos deudores que pertenecen al cluster
      percentages.append(np.sum(badclass)/len(badclass))
    percentages= np.array(percentages)
    return percentages



# 7. Calcule la característica que más diferencia dos clusters

Escriba una función que calcule la característica que es más diferente entre dos clusters dados. La función debe recibir el dataframe original con los datos, un modelo de clustering preentrenado y los índices de los clusters que se quieren comparar.

# 8. Calcule el número de clusters usando el método del codo

Diseñe una función que reciba un modelo de kmeans (no preentrenado) y encuentre un valor *óptimo* para el número de clusters usando la estrategia del codo. El valor óptimo es el máximo valor de $k$ tal que el incremento de la inercia entre $k-1$ y $k$ es al menos de un 2%. Su función no debe crear una nueva instancia del modelo de kmeans. Debe usar la función `km.set_params(n_clusters=k)` para fijar el número de clusters.

In [ ]:
def elbow(km, X, n):
    '''
    km: modelo KMeans
    X: arreglo de numpy con los datos
    n: valor máximo del número de clusters a explorar

    Returns:
    (k, inertia)
    k: número óptimo de clusters
    inertia: valor de la inercia correspondiente a k clusters
    '''
    ## Your code here
    k = 2
    arrinertia = []
    validator = True
    while (validator == True and k <= n):
      km = km.set_params(n_clusters= k)
      km = km.fit(X)
      arrinertia.append(km.inertia_)
      if (len(arrinertia) > 1):
        twopercent = arrinertia[-2]*0.02
        if (arrinertia[-2]-twopercent < arrinertia[-1]):
          validator = False
          inertia = arrinertia[-2]
      k+=1

    return (k-2, inertia)


In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.cluster import KMeans
 
 
df = pd.read_csv("credit-german.csv", sep=";")
df = pd.get_dummies(df)
escaler = MinMaxScaler()
X = escaler.fit_transform(df)
km = KMeans(n_clusters=5, random_state=10)
km.fit(X)
y = km.predict(X)
n= 10
#print(y, X)
print(len(y), len(X))
#print(np.unique(y))
result = np.array([117, 178, 276, 237, 192])
#np.allclose(num_elems(km, X), result)
print(age(km, X))
print(classes(km, X))
print(elbow(km, X, n))

1000 1000


NameError: ignored

In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.cluster import KMeans


df = pd.read_csv("credit-german.csv", sep=";")
df = pd.get_dummies(df)
escaler = MinMaxScaler()
X = escaler.fit_transform(df)
km = KMeans(random_state=10)
km.fit(X)
y = km.predict(X)
print(y.shape)
#print(y)
print(km.cluster_centers_.shape)

#res = np.array((14, 501.65992863324675))
#print(elbow(km, X[:100], 20))
#print(np.allclose(res, elbow(km, X[:100], 20)))

(1000,)
(8, 65)


In [ ]:
Xum = np.array([[3, 12, 540], [4, 20, 432], [5, 24, 1020], [6, 31, 102], [7, 15, 210]])
clusters = np.array([1 , 2 , 1, 1, 2])

#print(Xum[:,1])

#print(np.argwhere(Xum[:,1] > 15))

ages= []
for i in (np.unique(clusters)):
  arrages = Xum[np.argwhere(clusters==i), 1]
  print(Xum[np.argwhere(clusters==i), 1])
  promages = np.mean(arrages)
  ages.append(promages)

print(ages)




[[12]
 [24]
 [31]]
[[20]
 [15]]
[22.333333333333332, 17.5]


In [ ]:
nat = np.array([1, 3, 1, 3, 7])
nat2 = np.array([0, 2, 1, 5, 2])

print(nat - nat2)

[ 1  1  0 -2  5]


In [ ]:
np.bincount(nat)

array([0, 2, 0, 2, 0, 0, 0, 1])

In [ ]:
print(type(df.columns))

<class 'pandas.core.indexes.base.Index'>


In [ ]:
count = 0
for column in df:
    print(column)
    for data in df[column]:
      if (count % 2000 == 0):
        print(data)
      count += 1




In [ ]:
len(df.columns)

65

In [ ]:
df[0, 0]

KeyError: ignored

In [ ]:
from sklearn.cluster import KMeans
from sklearn.preprocessing import MinMaxScaler
 
## Your code here
df = pd.read_csv("credit-german.csv", sep=";")
df = pd.get_dummies(df)
scaler = MinMaxScaler()
X = np.array(scaler.fit_transform(df))
km = KMeans(random_state=10)
km.fit(X)

n = 2
m = 0

y = km.predict(X)
Xun = scaler.inverse_transform(X)
#Xun = escaler.inverse_transform(X) # desnormaliza los datos
max_difference = []

for column in range(len(df.columns)):
  cluster1 = Xun[np.argwhere(y == n), column]
  cluster2 = Xun[np.argwhere(y == m), column]

  cluster1_mean = np.mean(cluster1)
  cluster2_mean = np.mean(cluster2)

  #print(cluster1_mean)
  #print(cluster2_mean)

  max_difference.append( np.abs( cluster1_mean - cluster2_mean ) )

print(max_difference)
print( np.amax(max_difference) )
  
  # Guarda todas las diferencias en un dict.
  #most_differents[column] = max_difference

[6.558130978660781, 738.5905997056657, 1.171173657100809, 0.08820824135393672, 0.3305739514348786, 0.023730684326710813, 0.26609639440765265, 0.05684326710816777, 0.18165930831493743, 0.06346578366445915, 0.31650110375275936, 0.014532744665194995, 0.08544885945548197, 0.006622516556291391, 0.05619941133186167, 0.12858719646799116, 0.36350257542310527, 0.0, 0.07707873436350257, 0.014532744665194995, 0.0006438557763061067, 0.1371412803532009, 0.016004415011037526, 0.07625091979396614, 0.2626931567328918, 0.052336276674025024, 0.11810154525386315, 0.1524098601913172, 0.0035871964679911605, 0.026949963208241362, 0.1300588668138337, 0.04571376011773363, 0.21661147902869757, 0.052980132450331126, 0.06558130978660781, 0.33517292126563647, 0.04957689477557027, 0.09786607799852833, 0.14744297277409868, 0.33130978660779986, 0.035412067696835914, 0.01857983811626196, 0.38530169242089773, 0.038907284768211925, 0.006806475349521723, 0.04571376011773363, 0.041666666666666664, 0.07652685798381165, 0.

In [ ]:
## Scaler, tratamiento, etc
n = 1
m = 0
df = pd.read_csv("credit-german.csv", sep=";")
df = pd.get_dummies(df)
scaler = MinMaxScaler()
X = np.array(scaler.fit_transform(df))
km = KMeans(random_state=10)
km.fit(X)


y = km.predict(X)
Xun = scaler.inverse_transform(X)

max_difference = 0
feat = ''
val1 = 0
val2 = 0

for column in range(len(df.columns)):
  cluster1 = Xun[np.argwhere(y == n), column]
  cluster2 = Xun[np.argwhere(y == m), column]

  cluster1_mean = np.mean(cluster1)
  cluster2_mean = np.mean(cluster2)

  difference = np.abs( cluster1_mean - cluster2_mean )

  if difference > max_difference:
    max_difference = difference 



print(max_difference)



78.07967836257285


In [ ]:
result = most_different(df, km, 2, 0)
print(result)

327.6337647560804
('credit_amount', 2780.3932584269664, 2452.759493670886)


## Punto 7 !!!!!

In [ ]:
from sklearn.cluster import KMeans
from sklearn.preprocessing import MinMaxScaler

def most_different(df, km, n, m):
    '''
    df: dataframe con los datos
    km: modelo KMeans preentrenado
    n: índice del primer cluster
    m: índice del segundo cluster
    Returns:
    (feat, val1, val2)
    feat: string con el nombre de la característica
    val1: valor de la característica para el cluster m
    val2: valor de la característica para el cluster n
    '''
    ## Scaler, tratamiento, etc
    df = pd.read_csv("credit-german.csv", sep=";")
    df = pd.get_dummies(df)
    scaler = MinMaxScaler()


    X = np.array(scaler.fit_transform(df))
    km = KMeans(n_clusters=5, random_state=10)
    km.fit(X)

   
    y = km.predict(X)
    #Xun = scaler.inverse_transform(X)
    
    max_difference = 0
    feat = ''
    val1 = 0
    val2 = 0

    for column in range(len(df.columns)):
      cluster1 = X[np.argwhere(y == m ), column]
      cluster2 = X[np.argwhere(y == n ), column]

      cluster1_mean = np.mean(cluster1)
      cluster2_mean = np.mean(cluster2)

      difference = np.abs( cluster1_mean - cluster2_mean )

      if difference > max_difference:
        max_difference = difference 
        val1 = cluster1_mean
        val2 = cluster2_mean
        feat = df.columns[column]

    #print(max_difference)
    return (feat, val1, val2)


In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.cluster import KMeans


df = pd.read_csv("credit-german.csv", sep=";")
df = pd.get_dummies(df)
escaler = MinMaxScaler()
X = escaler.fit_transform(df)
km = KMeans(n_clusters=5, random_state=10)
km.fit(X)

res0, res1, res2 = ('property_magnitude_no known property', 0.9743589743589743, 0.043478260869565286)
res = most_different(df, km, 2, 4)
print(res)

('existing_credits_one', 0.890625, 0.007246376811594203)
